/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.entity.NguoiDungDAO;
import DAO.entity.NhanVienDAO;
import DAO.impl.NguoiDungDAOImpl;
import DAO.impl.NhanVienimpl;
import ENTITY.NguoiDung;
import ENTITY.NhanVien;
import UI.Controller.loginctr;
import UI.Panel.nhanvienn;
import UTIL.XDialog;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.net.URL;
import javax.swing.ImageIcon;


/**
 *
 * @author Admin
 */
public class dangnhap extends javax.swing.JFrame implements loginctr {

    /**
     * Creates new form dangnhap
     */
    public dangnhap() {
        initComponents();
         this.pack();
         setLocationRelativeTo(null);
    }
        

    @Override
  public void open() {
       this.setLocationRelativeTo(null);
    this.setVisible(true);
}

    /**
     *
     * @return
     */
 
    @Override
 
public void login() {
    try {
        int maNhanVien = Integer.parseInt(txtusername.getText().trim());
        String matKhau = new String(txtmk.getPassword()).trim();

        if (String.valueOf(maNhanVien).isEmpty() || matKhau.isEmpty()) {
            XDialog.alert("Vui lòng nhập đầy đủ mã nhân viên và mật khẩu!");
            return;
        }

        NhanVienDAO dao = new NhanVienimpl();
        boolean loginSuccess = dao.checkLogin(maNhanVien, matKhau);

        if (!loginSuccess) {
            XDialog.alert("Mã nhân viên hoặc mật khẩu sai!");
            return;
        }

        NhanVien nv = dao.findById(maNhanVien);
        XDialog.alert("Đăng nhập thành công!");

        if (nv.isChucVu()) {
            XDialog.alert("Chào quản lý: " + nv.getTenDangNhap());
            new quanly().setVisible(true);
        } else {
            XDialog.alert("Chào nhân viên: " + nv.getTenDangNhap());
            new nhanvienn().setVisible(true); 
        }

    } catch (NumberFormatException e) {
        XDialog.alert("Mã nhân viên phải là số!");
    } catch (Exception e) {
        e.printStackTrace();
        XDialog.alert("Lỗi hệ thống khi đăng nhập!");
    }
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtmk = new javax.swing.JPasswordField();
        cbmat = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 162, 97));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtusername.setPreferredSize(new java.awt.Dimension(70, 20));
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 270, 40));

        jButton1.setBackground(new java.awt.Color(105, 105, 105));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 370, 150, 40));

        jButton2.setBackground(new java.awt.Color(105, 105, 105));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 130, -1));

        txtmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmkActionPerformed(evt);
            }
        });
        getContentPane().add(txtmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 240, 38));

        cbmat.setText("mat");
        cbmat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbmatMouseClicked(evt);
            }
        });
        cbmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmatActionPerformed(evt);
            }
        });
        getContentPane().add(cbmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
exit();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmkActionPerformed
        // TODO add your handling code here:
if (cbmat.isSelected()) {
    txtmk.setEchoChar((char) 0); // hiện mật khẩu
} else {
    txtmk.setEchoChar('*'); // ẩn mật khẩu
}

    
    }//GEN-LAST:event_txtmkActionPerformed

    private void cbmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmatActionPerformed
        // TODO add your handling code here:
           if (cbmat.isSelected()) {
            txtmk.setEchoChar((char) 0); // Hiện mật khẩu
        } else {
            txtmk.setEchoChar('•'); // Ẩn mật khẩu (ký tự dấu chấm hoặc mặc định)
        }
    
    }//GEN-LAST:event_cbmatActionPerformed

    private void cbmatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbmatMouseClicked
        // TODO add your handling code here:
        cbmat.setText("Hiện mật khẩu");
    }//GEN-LAST:event_cbmatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dangnhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbmat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtmk;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
